# metallb-config.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-lb-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.228.100-192.168.228.200
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: main-l2-advertisement
  namespace: metallb-system
