apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: wso2-mysql-cluster
  namespace: mysql
spec:
  secretName: mypwds
  tlsUseSelfSigned: true
  instances: 3
  router:
    instances: 1
